# to run the service => docker compose up

volumes:
  mysql:
  mysql_config:

services:

  mysqldb:
    image: mysql:5.7.39
    ports:
    - 3306:3306
    environment:
      - MYSQL_USER=me
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=P@ssword1
      # ! do not use this in production
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
      # mapping project files into container
      - ./:/test

